trigger: none
parameters:
  - name: AgentPool
    displayName: Enter AgentPool Name
    type: string
    default: "appGatewayName"

  - name: CommonRepositry
    default: "self"
  
  - name: vmName
    displayName: Enter vmName 
    type: string
    default: "vmName"

  - name: vmSize
    displayName: Enter vmSize 
    type: string
    default: "vmSize"

  - name: vnetName
    displayName: Enter vnetName 
    type: string
    default: "vnetName"

  - name: appSubnetName
    displayName: Enter appSubnetName
    type: string
    default: "appSubnetName"

jobs:
  - job: Deploy_Arm_Template_For_AppVM
    pool: ${{ parameters.AgentPool }} 
    displayName: Deploy Arm Template For AppVM  
    workspace:
      clean: all 
    steps:
      - checkout: ${{parameters.CommonRepositry}}
        displayName: "Get CommonRepositry Templates"
        name: CheckoutCentralRepoTemplates
        path: "work"
      - task: AzureCLI@2
        displayName: "Deploy Arm Template For AppVM"
        inputs:
          azureSubscription: 3tiersetup_sc 
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
             az deployment group create \
             --name "Deploy-APPVM-Template"
             --resource-group "3tiersetup-rg" 
             --template-file "/Users/tanya/Desktop/3-tier-setup/arm-templates/CreateAppVM/azuredeploy.json"
             --parameters "/Users/tanya/Desktop/3-tier-setup/arm-templates/CreateAppVM/azuredeploy.parameters.json"
             --parameters \
             vmName={{parameters.vmName}} \
             vmSize={{parameters.vmSize}} \
             vnetName={{parameters.vnetName}} \
             appSubnetName={{parameters.appSubnetName}} \
             


    
  
