trigger: none
parameters:
  - name: AgentPool
    displayName: Enter AgentPool Name
    type: string
    default: "appGatewayName"

  - name: CommonRepositry
    default: "self"
  
  - name: vnetName
    displayName: Enter vnetName Name
    type: string
    default: "vnetName"

  - name: vnetAddressPrefix
    displayName: Enter vnetAddressPrefix Name
    type: string
    default: "vnetAddressPrefix"
  
jobs:
  - job: Deploy_Arm_Template_For_Vnet
    pool: ${{ parameters.AgentPool }} 
    displayName: Deploy Arm Template For Vnet  
    workspace:
      clean: all 
    steps:
      - checkout: ${{parameters.CommonRepositry}}
        displayName: "Get CommonRepositry Templates"
        name: CheckoutCentralRepoTemplates
        path: "work"
      - task: AzureCLI@2
        displayName: "Deploy Arm Template For Vnet"
        inputs:
          azureSubscription: 3tiersetup_sc 
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
             az deployment group create \
             --name "Deploy-PIP-Template"
             --resource-group "3tiersetup-rg" 
             --template-file "/Users/tanya/Desktop/3-tier-setup/arm-templates/CreateVnet/azuredeploy.json"
             --parameters "/Users/tanya/Desktop/3-tier-setup/arm-templates/CreateVnet/azuredeploy.parameters.json"
             --parameters \
             vnetName={{parameters.vnetName}} \
             vnetAddressPrefix={{parameters.vnetAddressPrefix}} \
             
             
             


    
  
