trigger: none
parameters:
  - name: AgentPool
    displayName: Enter AgentPool Name
    type: string
    default: "appGatewayName"

  - name: CommonRepositry
    default: "self"
  
  - name: appVMName
    displayName: Enter appVMName Name
    type: string
    default: "appVMName"

jobs:
  - job: Deploy_Arm_Template_For_SQLServer
    pool: ${{ parameters.AgentPool }} 
    displayName: Deploy Arm Template For SQLServer  
    workspace:
      clean: all 
    steps:
      - checkout: ${{parameters.CommonRepositry}}
        displayName: "Get CommonRepositry Templates"
        name: CheckoutCentralRepoTemplates
        path: "work"
      - task: AzureCLI@2
        displayName: "Deploy Arm Template For CreateSQLServer"
        inputs:
          azureSubscription: 3tiersetup_sc 
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
             az deployment group create \
             --name "Deploy-PIP-Template"
             --resource-group "3tiersetup-rg" 
             --template-file "/Users/tanya/Desktop/3-tier-setup/arm-templates/CreateSQLServer/azuredeploy.json"
             --parameters "/Users/tanya/Desktop/3-tier-setup/arm-templates/CreateSQLServer/azuredeploy.parameters.json"
             --parameters \
             appVMName={{parameters.appVMName}} \
             
             


    
  
